#!/bin/bash

# This is a yadm bootstrap file, executed after the initial clone of the dotfiles repository.

cd "$HOME"

HOSTNAME_SHORT=$(hostname | cut -d'.' -f1)
# echo "Short hostname: $HOSTNAME_SHORT"

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:pranavmishra90/dotfiles.git"

yadm checkout $HOSTNAME_SHORT || yadm checkout develop
echo "Yadm is on branch: $(yadm branch --show-current -v)"
echo "Yadm remote is: $(yadm remote -v)"
printf "\n\n"

# Clone down the submodules tied to this repository
echo "Cloning yadm submodules"
yadm submodule update --init --recursive
echo "Completed cloning yadm submodules"
printf "\n\n"


# Move the pyproject.toml file so that uv does not think that the home directory is a python project
mv ~/pyproject.toml ~/yadm/pyproject.toml

